########################################################
|exerciseicon__T| Exercici 01_07. El quadrat d'un número
########################################################

.. rubric:: Context

* Carpeta de lliurament: ``01_07_quadrat_numero/``

* Continguts relacionats: :doc:`instruccions_comprovacio`

* Com lliurar-lo: :ref:`instruccions <instruccions_git>`

* [✓] Exercici amb :ref:`autoavaluació<descripcio_exercicis_autoavaluacio>`

.. rubric:: Enunciat

Desenvolupa un programa que demani un número i
escrigui el número al quadrat.

Una possible interacció:

.. code-block:: console
    :emphasize-lines: 3

    $ python3 quadratnum.py
    Donam un número:
    4
    El quadrat de 4 és 16

Per comprovar que el teu programa passa les proves, executa la següent
comanda dins de la carpeta de l'exercici:

.. code-block:: console

    $ prgtest.sh

Quan no hi ha error, el programa t'ho indicarà amb el missatge:

.. code-block:: console

    El programa quadratnum.py ha passat totes les proves

En cas, però que hi trobi algun error, el programa et donarà informació per que
puguis identificar el problema i resoldre'l.

Un exemple de sortida d'error seria:

.. code-block:: console

    $ prgtest.sh
    Error
    =====
    No es troba el programa quadratnum.py
    Assegura't que has posat el nom correcte al teu programa

El que t'està indicant aquest error és que el programa de test no troba el teu
programa. És possible que hagis escrit el nom del fitxer malament. Et recomano
que el repassis amb compte.

Imagina que has escrit com a nom ``cuadratnum.py`` (fixat la ``c`` en comptes de
la ``q``). En aquest cas, potser el voldràs reanomenar. Una manera és seguir les
instruccions:

* tanca l'editor amb el teu programa si encara el tens obert.

* a la consola escriu:

  .. code-block:: console

        $ mv cuadratnum.py quadratnum.py

* torna a executar la prova.

Un altre exemple de sortida d'error seria:

.. code-block:: console
    :linenos:

    $ prgtest.sh
    Test nr. 1: Error

    Entrada
    =======
    4

    Sortida esperada
    ================
    Donam un número
    El quadrat de 4 és 16

    Sortida trobada
    ===============
    Donam un número
    El quadrat de 4 és 17

    Diferència
    ==========
    2c2
    < El quadrat de 4 és 16
    ---
    > El quadrat de 4 és 17

A la línia 1, el programa de proves et diu que ha trobat un error. El nr. de
l'error et servirà com a referència per que m'ho comentis en cas que no trobis
la manera de resoldre'l.

A la línia 6 hi trobes la entrada que el programa de prova ha introduït al teu
programa. En aquest cas ha introduït el nr. 4 doncs el teu programa espera que
l'introdueixin un número. Si li calguessin més dades, aquí hi apareixerien
totes, cadascuna en la seva línia.

A partir de la línia 10 hi apareix totes les sortides que s'esperaven del teu
programa. Es tracta de tot el que surt amb ``print()`` en fer l'execució.

Fixa't que també inclou el text amb la pregunta que fa el teu programa als
usuaris.

A partir de la línia 15, et mostra la sortida que realment ha fet el
teu programa amb l'entrada indicada.

A partir de la línia 20, et mostra la sortida de la utilitat ``diff`` que et pot
ajudar a identificar les diferències entre l'esperat i el trobat.

La manera que et proposo que procedeixis si no has vist el problema amb la
informació que et mostra el programa de prova és:

* executa el teu programa

* introdueix per teclat el que se t'indica a la secció *Entrada* (línia 6). En
  aquest cas un 4

* comprova que el teu programa estigui escrivint tot allò que s'espera (mira
  secció *Sortida esperada* (línia 10 en davant)

Si tot i així no te'n surts, demana ajut. No et preocupis, amb la pràctica es fa
més fàcil.

Recorda finalment registrar els canvis en ``git`` i pujar el teu resultat al
repositori remot.

